### ISSUE TITLE
unnecessary square bracket

### ISSUE THREAD

**Issue by rupc** [asararatnakar/FabricNodeApp1.0#1]
Hi, I take a look at artifacts/base.yaml and find unnecessary square bracket pair.
https://github.com/asararatnakar/FabricNodeApp1.0/blob/master/artifacts/base.yaml#L46

**Comment by asararatnakar** [comment]
@rupc I haven't noticed your message.

square bracket are necessary , **ROOT CAS** would expect an array not a single value.
you can refer the same [here](https://github.com/hyperledger/fabric/blob/master/sampleconfig/orderer.yaml#L35)

For example, you would see the below crash in **orderer** if you don't give the square bracket
I removed the square brackets and here is the crash 
```
2017-08-21 21:16:54.984 UTC [orderer/main] main -> INFO 001 Starting orderer:
 Version: 1.0.0
 Go version: go1.7.5
 OS/Arch: linux/amd64
2017-08-21 21:16:55.001 UTC [orderer/localconfig] Load -> CRIT 002 Error unmarshaling config into struct: 1 error(s) decoding:

* 'General.TLS.RootCAs': source data must be an array or slice, got string
panic: Error unmarshaling config into struct:1 error(s) decoding:

* 'General.TLS.RootCAs': source data must be an array or slice, got string

goroutine 1 [running]:
panic(0xb31bc0, 0xc4202a89f0)
	/opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hyperledger/fabric/vendor/github.com/op/go-logging.(*Logger).Panic(0xc4201e3170, 0xc42029b6e0, 0x2, 0x2)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/op/go-logging/logger.go:188 +0xd0
github.com/hyperledger/fabric/orderer/localconfig.Load(0xc4201e3c20)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/localconfig/config.go:237 +0x530
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:69 +0x309
```
